public with sharing class Util {

    public static String DRAFT = 'Draft';
    public static String NEWVAL = 'New';
    public static String QUANTITY = 'Quantity';
    public static String UNITPRICE = 'UnitPrice';
    public static String PRODUCT2ID = 'Product2Id';
    public static String PRICEBOOKENTRYID = 'PricebookEntryId';
    public static String ACCOUNTNUMBER = 'accountNumber';
    public static String ORDERNUMBER = 'orderNumber';
    public static String TYPE = 'type';
    public static String STATUS = 'status';
    public static String NAME = 'name';
    public static String CODE = 'code';
    public static String UNITPRICE_SMALL = 'unitPrice';
    public static String QUANTITY_SMALL = 'quantity';
    public static String ORDERPRODUCTS = 'orderProducts';
    public static String CONTENT_TYPE = 'Content-Type';
    public static String APPLICATION_JSON = 'application/json';
    public static String ACTIVATED = 'Activated';
    public static String POST = 'POST';
    public static String MOCKBODY = '{"example":"test"}';
    public static String PUSHPRODUCTS = 'PushProducts';
}